# -*- mode: ruby -*- 
# vi: set ft=ruby : 
hosts = {   
"n1" => "192.168.77.20",   
"n2" => "192.168.77.21",   
"n3" => "192.168.77.22",   
"n4" => "192.168.77.23" 
} 
Vagrant.configure("2") do |config|   

# always use Vagrants insecure key   
config.ssh.insert_key = false   

# forward ssh agent to easily ssh into the different machines   
config.ssh.forward_agent = true    

check_guest_additions = false   
functional_vboxsf     = false    

config.vm.box = "bento/ubuntu-18.04"  
hosts.each do |name, ip|
     config.vm.hostname = name
     config.vm.define name do |machine|
            machine.vm.network :private_network, ip: ip
            machine.vm.provider "virtualbox" do |v|
                     v.name = name       
                 end
                      end
                         end
                          end
 
