-
  name: Deploy a web application
  hosts: windows
  vars: 
    OsArchitectur: powershell.exe (Get-WmiObject Win32_Processor).AddressWidth
  tasks:

      
      
      
      
      
      
    - name: Visual c++ installation
      win_package:
        path: C:\installer\servers\vc_redist.x64.exe
        product_id: '{323dad84-0974-4d90-a1c1-e006c7fdbb7d}'
        arguments: /install /passive /norestart

    - name: Run an executable and send data to the stdin for the executable
      win_shell: msiexec -i C:\installer\servers\mysql-installer\mysql-8.0.13-winx64.msi -quiet 

    - name: Run mysql connector
      win_shell: msiexec -i C:\installer\servers\mysql-connector-odbc\mysql-connector-odbc-5.3.11-winx64.msi -quiet

    - name: Heidi SQL installation
      win_shell: C:\installer\servers\HeidiSQL\HeidiSQL_9.5.0.5196_Setup.exe /SP /SILENT
    
    - name: Execute powershell command
      win_shell: echo {{ OsArchitectur }}
      register: command_output
      tags:
         - evaluate1

    - debug: var=command_output.stdout
      tags: 
         - evaluate2

    - name: Evaluate output and print if this works properly
      win_shell: echo si-charcha
      when: command_output.stdout.find("*64*") == -1
      tags:
         - evaluate3
      
           #tags:
           #- evaluate2
      #   - name: Execute CPlusPlusRedist installation
        #win_package:
        #path: C:\installer\CPlusPlusRedist\2013\en\vcredist_x64.exe 
        #state: present

        #- name: Execute local msi of mysql installer
        #win_package:
        #path: C:\installer\servers\mysql-conector-odbc\mysql-connector-odbc-5.3.11-winx64.msi
        #state: present

        #- name: Execute local msi of mysql installer
        #win_package:
        #path: C:\installer\servers\HeidiSQL\HeidiSQL_9.5.0.5196_Setup.exe
        #state: present

        #- name: Execute local msi of mysql installer
        #win_package:
        #path: C:\installer\servers\replicatorManager\ReplicatorManager.exe
        #state: present

